### ISSUE TITLE
Fetch release archives from PyPI

### ISSUE THREAD

**Issue by jlstevens** [conda-forge/param-feedstock#5]
In #4 I updated the recipe so that users get the correct version from the git tags in param's repository. 

A better approach for release versions might be to fetch the archive from PyPI which means we can use the checksum and follow the guidelines better. For development versions, the only way to get correct versions will be to use git sources.

**Comment by CJ-Wright** [comment]
I don't know if I understand this issue. Would you mind clarifying what is wrong with getting the tags from github?

**Comment by jakirkham** [comment]
This was done in PR ( https://github.com/conda-forge/param-feedstock/pull/6 ) IIUC.

As to PyPI vs. GitHub, this discussion at least goes back to the beginning of conda-forge (if not earlier). So I don't think we are going to solve it in this issue (maybe ever). The best I think we can hope for is clear, unbiased info about both options so that packagers can make the right choice for their package, which is really what we care about in the end. Raised issue ( https://github.com/conda-forge/conda-forge.github.io/issues/575 ) on this point.

**Comment by jlstevens** [comment]
Thanks @jakirkham . As you say, this was done for this project in #6.

At any rate, documenting the pros and cons makes sense at a more global level. As for this issue, I'll close it now.
